### ISSUE TITLE
SSA view over ObsCore

### ISSUE THREAD

**Issue by molinaro-m** [vforchi/SSAPServer#1]
Hi,
I'm trying to run SSAPServer on top of a TAPlib TAP service on my laptop.

I cannot configure it properly because there's the TBD on the ssa view over TAP, i.e. I don't know how to create and configure that specific view.

Can you add some documentation on that specific point?

Thanks!
    Marco

**Comment by vforchi** [comment]
Hi Marco, 
sorry for the very late reply, for some reason I never saw this issue.
We recenlty added the SQL to create the view we are using:
https://github.com/vforchi/SSAPServer/blob/master/sql/create_view_ssa.sql
